In [967]:
import numpy as np

<h4>1.1.	Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5</h4>

In [968]:
my_array = np.arange(5, 101, 5)
print("my_array:", my_array)

my_array: [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


<h4>2.1.	Из полученного массива получить массив с кратными 10 числами</h4>

In [969]:
my_array_2 = my_array[my_array % 10 == 0]
print("my_array_2:", my_array_2)

my_array_2: [ 10  20  30  40  50  60  70  80  90 100]


<h4>3.1.	Получить двумерный массив с двумя столбцами</h4>

In [970]:
my_array_3 = np.array([[1,2],[3,4],[5,6]])
print("my_array_3:\n", my_array_3)

my_array_3:
 [[1 2]
 [3 4]
 [5 6]]


<h4>4.1.	Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5</h4>

In [971]:
my_second_array = my_array_3 - 5
print("my_second_array:\n", my_second_array)

my_second_array:
 [[-4 -3]
 [-2 -1]
 [ 0  1]]


<h4>5.1.	Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.</h4>

In [972]:
my_combined_array = np.concatenate((my_array_3, my_second_array), axis=1)
print("my_combined_array:\n", my_combined_array.T)

my_combined_array:
 [[ 1  3  5]
 [ 2  4  6]
 [-4 -2  0]
 [-3 -1  1]]


<h4>6.1.	Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы</h4>

In [973]:

""

''

<h4>7.1.	Оставить только те значения, которые не изменились после деления</h4>

<h4>8.1.	Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки</h4>

In [974]:
my_array_4 =[
    [21,43,43],
    [65,35,99],
    [54,88,31]
]

my_array_4 = my_array_4[::-1]
print("my_array_4:\n", my_array_4)

my_array_4:
 [[54, 88, 31], [65, 35, 99], [21, 43, 43]]


<h4>9.1.	Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().</h4>

In [975]:
means = np.mean(my_array_4, axis=1)
medians = np.median(my_array_4, axis=1)
std_devs = np.std(my_array_4, axis=1)
print("9.1. Means:", means)
print("    Medians:", medians)
print("    Standard Deviations:", std_devs)

9.1. Means: [57.66666667 66.33333333 35.66666667]
    Medians: [54. 65. 43.]
    Standard Deviations: [23.41414577 26.1448954  10.37089946]


<h4>10.1.	Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк</h4>

In [976]:
normalized_array = my_array_4 / np.max(my_array_4,axis=1, keepdims=True)
print("10.1. normalized_array:\n", normalized_array)

10.1. normalized_array:
 [[0.61363636 1.         0.35227273]
 [0.65656566 0.35353535 1.        ]
 [0.48837209 1.         1.        ]]


<h4>2.1.	Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. Описание данных смотрите ниже.
Изучите полученные данные:</h4>

<h4>

In [977]:
import pandas as pd
df = pd.read_csv("global_population_trends.csv")
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55            63.0      37.342       7.027   
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38            61.0      32.516       8.266   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[1073 rows x 12 columns]

<h4>2.2.	 Считайте несколько первых записей таблицы (head())</h4>

In [978]:
print("Первые записи таблицы:")
print(df.head())

Первые записи таблицы:
       Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0            

<h4>2.3.	 Определите размерность данного фрейма (shape())</h4>

In [979]:
print("\nРазмерность данных (строки, столбцы):")
print(df.shape)


Размерность данных (строки, столбцы):
(1073, 12)


<h4>2.4 Выведите название заголовков столбцов фрейма (columns)</h4>

In [980]:
print("\nЗаголовки столбцов:")
print(df.columns)


Заголовки столбцов:
Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')


<h4>2.5.	Получите описание всех переменных (полей) (info())</h4>

In [981]:
print("\nОписание переменных:")
print(df.info())


Описание переменных:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB
None


<h4>2.6.	 Удалите строки, не содержащие значения в столбце «Total Population» - “-” </h4>

In [982]:
df = df[df["Total Population"] != "-"]
print("\nПервые записи после удаления строк с пропущенными значениями:")
print(df.head())


Первые записи после удаления строк с пропущенными значениями:
       Country  Year Total Population Urban Population Rural Population  \
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6      Albania  2018        2,866,376        1,728,969        1,137,407   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   
6                105            79.0      10.517       8.308           1.44   

  Infant Mo

<h4>2.7. Получение описательной статистики по переменным:</h4>

In [983]:
max_values = df.max()
print("Максимальные значения по столбцам:")
print(max_values)

min_values = df.min()
print("\nМинимальные значения по столбцам:")
print(min_values)

print("\nОписательная статистика:")
print(df.describe())

Максимальные значения по столбцам:
Country                    Zimbabwe
Year                           2021
Total Population             99,258
Urban Population         99,876,265
Rural Population            998,397
Population Density               99
Life Expectancy                85.0
Birth Rate                   46.127
Death Rate                     21.7
Fertility Rate                7.023
Infant Mortality Rate           9.9
Growth Rate                     5.0
dtype: object

Минимальные значения по столбцам:
Country                  Afghanistan
Year                            2018
Total Population           1,057,198
Urban Population                   -
Rural Population                   -
Population Density                 -
Life Expectancy                    -
Birth Rate                       0.0
Death Rate                       0.0
Fertility Rate                     -
Infant Mortality Rate              -
Growth Rate                     -1.0
dtype: object

Описательная статистика:


<h4>2.8. Сортировка данных по нескольким критериям:</h4>

In [984]:
df.loc[df["Total Population"] == "-", "Total Population"] = "0"
df["Total Population"] = df["Total Population"].str.replace(",", "").astype(float)
df = df.sort_values(by=['Year', 'Total Population'], ascending=[True, False])
df


C:\Users\ACER\AppData\Local\Temp\ipykernel_7116\370242326.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total Population"] = df["Total Population"].str.replace(",", "").astype(float)


Country  Year  Total Population Urban Population  \
202                      China  2018      1.402760e+09      829,760,595   
432                      India  2018      1.369003e+09      465,871,825   
1019             United States  2018      3.268382e+08      268,844,029   
437                  Indonesia  2018      2.670668e+08      147,754,731   
725                   Pakistan  2018      2.197315e+08       80,566,744   
...                        ...   ...               ...              ...   
907   St. Martin (French Part)  2021      3.194800e+04                -   
137     British Virgin Islands  2021      3.112200e+04           15,225   
733                      Palau  2021      1.802400e+04           14,686   
664                      Nauru  2021      1.251100e+04           12,511   
997                     Tuvalu  2021      1.120400e+04            7,259   

     Rural Population Population Density Life Expectancy  Birth Rate  \
202       572,999,405                149            78.0      10.860   
432       903,131,481                460            71.0      17.651   
1019       57,994,170                 36            79.0      11.600   
437       119,312,112                142            70.0      17.179   
725       139,164,735                285            66.0      28.594   
...               ...                ...             ...         ...   
907                 -                  -            80.0      15.053   
137            15,897                  -            74.0       7.634   
733             3,338                  -               -      13.400   
664                 -                  -            64.0      27.560   
997             3,945                  -            65.0      23.484   

      Death Rate Fertility Rate Infant Mortality Rate Growth Rate  
202        7.080          1.554                   6.4         0.0  
432        6.644          2.177                  29.8         1.0  
1019       8.678           1.73                   5.6         1.0  
437        7.496          2.234                  20.8         1.0  
725        6.843          3.685                  57.4         2.0  
...          ...            ...                   ...         ...  
907        4.911          2.415                     -        -2.0  
137        7.613          1.005                   9.9         1.0  
733       10.200            0.0                  15.1         0.0  
664        6.633          3.519                  23.2         2.0  
997       10.159          3.163                  18.1         1.0  

[864 rows x 12 columns]

<h4>2.9. Вывод названия страны с максимальной численностью населения:</h4>

In [985]:
country_with_max_population = df[df['Total Population'] == df['Total Population'].max()]['Country'].values[0]
print(f"\nСтрана с максимальной численностью населения: {country_with_max_population}")


Страна с максимальной численностью населения: China


<h4>2.10. Вывод названия страны с минимальной численностью населения:</h4>

In [986]:
country_with_min_population = df[df['Total Population'] == df['Total Population'].min()]['Country'].values[0]
print(f"Страна с минимальной численностью населения: {country_with_min_population}")

Страна с минимальной численностью населения: Tuvalu


<h4>2.11. Экспорт фрейма в MS Excel:</h4>

In [987]:
df.to_excel("population_data.xlsx", index=False)
print("\nДанные экспортированы в population_data.xlsx")


Данные экспортированы в population_data.xlsx
